# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - restaurant-ruczaj

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4c15a9249cb420896bfc13ab957cb09 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_472921bc4e95433ab185a0ba3b0024eb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4c15a9249cb420896bfc13ab957cb09 }}/restaurant-ruczaj:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restaurant-ruczaj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0cfc81b8a31040d0aa8355c7b62fe5d0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4c15a9249cb420896bfc13ab957cb09 }}/restaurant-ruczaj:${{ github.sha }}'